INSERT INTO Book (Genre, Price, Title, Descriptions, Image_URL)
VALUES
    ('Dystopian', 12.501, '1984', 'A chilling vision of a totalitarian future.', '1984.jpg'),
    ('Biography', 8.996, 'The Diary of a Young Girl', 'The poignant diary of Anne Frank.', 'anne_frank.jpg'),
    ('Self-help', 15.509, 'Atomic Habits', 'A guide to forming good habits.', 'atomic_habits.jpg'),
    ('Memoir', 18.754, 'Becoming', 'Michelle Obama''s inspiring memoir.', 'becoming.jpg'),
    ('Science Fiction', 22.500, 'Dune', 'A complex saga of politics and power.', 'dune.jpg'),
    ('Romance', 10.995, 'The Fault in Our Stars', 'A heartbreaking love story.', 'fault_stars.jpg'),
    ('Thriller', 14.502, 'Gone Girl', 'A gripping psychological thriller.', 'gone_girl.jpg'),
    ('Fantasy', 20.031, 'Harry Potter', 'A magical journey of a young wizard.', 'harry_potter.jpg'),
    ('Classic', 7.992, 'To Kill a Mockingbird', 'A timeless tale of justice and race.', 'mockingbird.jpg'),
    ('Fantasy', 12.253, 'The Hobbit', 'An epic adventure to reclaim a treasure.', 'the_hobbit.jpg'),
    ('Children', 5.995, 'Charlotte''s Web', 'A heartwarming story of friendship between a pig and a spider by E.B. White.', 'charlottes_web.jpg'),
    ('Horror', 8.991, 'Dracula', 'A gothic horror novel about the infamous Count Dracula by Bram Stoker.', 'dracula.jpg'),
    ('Mystery', 10.992, 'The Girl with the Dragon Tattoo', 'A gripping mystery thriller by Stieg Larsson featuring journalist Mikael Blomkvist and hacker Lisbeth Salander.', 'dragon_tattoo.jpg'),
    ('History', 11.997, 'Guns, Germs, and Steel', 'Jared Diamond''s analysis of the factors shaping human societies.', 'guns_germs_steel.jpg'),
    ('History', 12.497, 'The History of the World', 'J.M. Roberts'' comprehensive account of the history of humankind.', 'history_world.jpg'),
    ('Science Fiction', 8.493, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams'' hilarious sci-fi adventure through the cosmos.', 'hitchhiker.jpg'),
    ('Travel', 10.991, 'Into the Wild', 'Jon Krakauer''s true story of Christopher McCandless and his journey into the Alaskan wilderness.', 'into_the_wild.jpg'),
    ('Cookbooks', 17.994, 'The Joy of Cooking', 'Irma S. Rombauer''s timeless and comprehensive cookbook for home cooking.', 'joy_of_cooking.jpg'),
    ('Travel', 15.000, 'Lonely Planet Vietnam', 'A detailed travel guide to exploring Vietnam, offering tips and insights for travelers.', 'lonely_planet_vietnam.jpg'),
    ('Psychology', 9.500, 'Man''s Search for Meaning', 'Viktor E. Frankl''s inspiring memoir and exploration of finding purpose in life, even in adversity.', 'mans_search.jpg'),
    ('Children', 6.750, 'Matilda', 'Roald Dahl''s story of a remarkable girl with extraordinary talents who stands up to injustice.', 'matilda.jpg'),
    ('Poetry', 10.250, 'Milk and Honey', 'Rupi Kaur''s collection of poignant poems and prose about love, loss, and healing.', 'milk_and_honey.jpg'),
    ('Classic', 7.990, 'Pride and Prejudice', 'Jane Austen''s timeless tale of love, family, and social expectations.', 'pride_prejudice.jpg'),
    ('Cookbooks', 20.000, 'Salt, Fat, Acid, Heat', 'Samin Nosrat''s comprehensive guide to mastering the elements of great cooking.', 'salt_fat_acid_heat.jpg'),
    ('History', 12.500, 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari''s exploration of the history and impact of human evolution.', 'sapiens.jpg'),
    ('Biography', 14.750, 'Steve Jobs', 'Walter Isaacson''s detailed biography of Apple co-founder Steve Jobs.', 'steve_jobs.jpg'),
    ('Poetry', 11.250, 'The Sun and Her Flowers', 'Rupi Kaur''s follow-up poetry collection about growth, healing, and self-discovery.', 'sun_and_her_flowers.jpg'),
    ('Fiction', 10.000, 'The Alchemist', 'Paulo Coelho''s novel about a shepherd''s spiritual journey in search of his destiny.', 'the_alchemist.jpg'),
    ('Art', 22.500, 'The Art Book', 'An extensive overview of art history and the most influential works through time.', 'the_art_book.jpg'),
    ('Science', 16.750, 'The Body', 'Bill Bryson''s engaging exploration of the marvels and mysteries of the human body.', 'the_body.jpg'),
    ('Horror', 14.990, 'The Shining', 'Stephen King''s chilling tale of a family isolated in a haunted hotel.', 'the_shining.jpg'),
    ('Graphic Novel', 12.500, 'Watchmen', 'Alan Moore and Dave Gibbons''s groundbreaking graphic novel exploring morality and heroism in a dystopian world.', 'watchmen.jpg');