
-- Users --
CREATE TABLE Users(
	Users_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Email VARCHAR(254) NOT NULL UNIQUE,
	User_name VARCHAR(20) NOT NULL,
	Passwords VARCHAR(100) NOT NULL,
    Money_spent NUMERIC(15,3) NOT NULL,
    PFP_URL VARCHAR(100)
);
-- Contact --
CREATE TABLE Contact(
	Contact_ID INT PRIMARY KEY AUTO_INCREMENT,
	Names VARCHAR(20) NOT NULL,
	Email VARCHAR(254) NOT NULL,
	Title VARCHAR(100) NOT NULL,
	Messages TEXT,
    Contact_date DATE DEFAULT CURRENT_TIMESTAMP
);

-- Order --
CREATE TABLE Orders(
	Order_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Total_money NUMERIC(15,3) NOT NULL,
	Users_ID INT UNSIGNED NOT NULL,
    Order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (Users_ID) REFERENCES Users(Users_ID) ON DELETE CASCADE
);

-- Book --
CREATE TABLE Book(
	Book_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Genre VARCHAR(20),
	Price NUMERIC(15,3) NOT NULL CHECK(Price >= 0),
	Title VARCHAR(100) NOT NULL,
	Descriptions TEXT,
    Image_URL VARCHAR(100)
);
-- Review --
CREATE TABLE Review (
	Review_ID INT PRIMARY KEY AUTO_INCREMENT,
	Review_description TEXT NOT NULL,
	Review_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	Stars INT NOT NULL CHECK (Stars >= 0 AND Stars <= 5),
	Likes INT UNSIGNED DEFAULT 0,
	Disikes INT UNSIGNED DEFAULT 0
);
-- Order Item--
CREATE TABLE Order_item(
	Order_ID INT UNSIGNED,
	Book_ID INT UNSIGNED,

	PRIMARY KEY(Order_ID, Book_ID),
	
	Quantity INT UNSIGNED,
	Review_ID INT UNSIGNED,
    Conditions VARCHAR(10) NOT NULL,
	
	FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID) ON DELETE CASCADE,
	FOREIGN KEY (Book_ID) REFERENCES Book(Book_ID) ON DELETE CASCADE
);


CREATE TABLE Admins(
	Admins_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Email VARCHAR(254) NOT NULL UNIQUE,
	Admin_name VARCHAR(20) NOT NULL,
	Passwords VARCHAR(100) NOT NULL,
    PFP_URL VARCHAR(100)
);