INSERT INTO Books (title, descriptions, price, genre, image_link) VALUES
    ('The Midnight Library', 'A story exploring the infinite possibilities of life.', 15.99, 'Fiction', 'midnight_library.jpg'),
    ('Atomic Habits', 'An easy and proven way to build good habits and break bad ones.', 22.50, 'Self-help', 'atomic_habits.jpg'),
    ('Sapiens: A Brief History of Humankind', 'A deep dive into the history and evolution of Homo sapiens.', 18.75, 'History', 'sapiens.jpg'),
    ('The Alchemist', 'A tale about following your dreams and listening to your heart.', 14.00, 'Adventure', 'alchemist.jpg'),
    ('Python Crash Course', 'A fast-paced introduction to programming with Python.', 28.99, 'Programming', 'python_crash_course.jpg'),
    ('To Kill a Mockingbird', 'A classic novel about race and justice in America.', 12.99, 'Classics', 'to_kill_a_mockingbird.jpg'),
    ('Dune', 'An epic science fiction saga set on a desert planet.', 19.95, 'Science Fiction', 'dune.jpg'),
    ('Becoming', 'An intimate memoir by former First Lady Michelle Obama.', 20.50, 'Biography', 'becoming.jpg'),
    ('The Art of War', 'An ancient text on strategy and leadership.', 10.00, 'Philosophy', 'art_of_war.jpg'),
    ('Harry Potter and the Philosopher''s Stone', 'The magical beginning of the Harry Potter series.', 25.00, 'Fantasy', 'harry_potter.jpg'),
    ('Educated', 'A memoir about one woman''s quest for education despite an unconventional upbringing.', 16.99, 'Memoir', 'educated.jpg'),
    ('Goodnight Moon', 'A beloved bedtime story that has charmed generations of readers.', 8.50, 'Children', 'goodnight_moon.jpg'),
    ('A Brief History of Time', 'Stephen Hawking''s iconic exploration of cosmology and the universe.', 14.75, 'Science', 'a_brief_history_of_time.jpg'),
    ('The Hitchhiker''s Guide to the Galaxy', 'A hilarious science fiction adventure through space.', 12.95, 'Humor', 'hitchhikers_guide.jpg'),
    ('The Joy of Cooking', 'An essential and timeless cookbook for every kitchen.', 30.00, 'Cooking', 'joy_of_cooking.jpg'),
    ('The Catcher in the Rye', 'A classic coming-of-age story about teenage rebellion and identity.', 13.99, 'Classics', 'catcher_in_the_rye.jpg'),
    ('Thinking''s Fast and Slow', 'An exploration of the two systems that drive our thinking and decision-making.', 17.50, 'Psychology', 'thinking_fast_and_slow.jpg'),
    ('The Road', 'A haunting post-apocalyptic tale of survival and hope.', 14.25, 'Dystopian', 'the_road.jpg'),
    ('Pride and Prejudice', 'Jane Austen''s timeless story of love and societal expectations.', 11.99, 'Romance', 'pride_and_prejudice.jpg'),
    ('The Lean Startup', 'A guide to building successful startups using innovative techniques.', 21.95, 'Business', 'lean_startup.jpg'),
    ('The Hobbit', 'A delightful fantasy adventure that serves as a prequel to The Lord of the Rings.', 18.75, 'Fantasy', 'the_hobbit.jpg'),
    ('The Subtle Art of Not Giving a F*ck', 'A counterintuitive approach to living a good life.', 19.50, 'Self-help', 'subtle_art.jpg'),
    ('1984', 'George Orwell''s dystopian vision of a totalitarian future.', 15.00, 'Science Fiction', '1984.jpg'),
    ('The Great Gatsby', 'A tragic tale of love, wealth, and the American Dream.', 10.99, 'Classics', 'great_gatsby.jpg'),
    ('Rich Dad Poor Dad', 'A personal finance book that changes perspectives on money and investing.', 14.95, 'Finance', 'rich_dad_poor_dad.jpg'),
    ('The Secret', 'A self-help book exploring the power of positive thinking and the law of attraction.', 16.75, 'Self-help', 'the_secret.jpg'),
    ('The Book Thief', 'A beautifully narrated story set in Nazi Germany, seen through the eyes of a young girl.', 13.50, 'Historical Fiction', 'the_book_thief.jpg'),
    ('The Shining', 'A gripping horror story of isolation and madness in a haunted hotel.', 18.25, 'Horror', 'the_shining.jpg'),
    ('A Man Called Ove', 'A heartwarming and humorous story about friendship and second chances.', 14.99, 'Fiction', 'a_man_called_ove.jpg'),
    ('The Power of Now', 'A guide to spiritual enlightenment and living in the present moment.', 19.95, 'Spirituality', 'the_power_of_now.jpg'),
    ('The Kite Runner', 'A tale of friendship, betrayal, and redemption set in Afghanistan.', 12.99, 'Drama', 'the_kite_runner.jpg'),
    ('Gone Girl', 'A psychological thriller full of twists and deceit.', 14.50, 'Thriller', 'gone_girl.jpg'),
    ('The Hunger Games', 'A dystopian story of survival and revolution.', 15.75, 'Young Adult', 'hunger_games.jpg'),
    ('The Adventures of Sherlock Holmes', 'Classic detective stories featuring the brilliant Sherlock Holmes.', 11.25, 'Mystery', 'sherlock_holmes.jpg'),
    ('The Little Prince', 'A philosophical tale disguised as a childre''s story, full of profound insights.', 9.99, 'Philosophy', 'the_little_prince.jpg'),
    ('Where the Crawdads Sing', 'A coming-of-age mystery set in the marshes of North Carolina.', 18.50, 'Fiction', 'where_the_crawdads_sing.jpg'),
    ('The Fellowship of the Ring', 'The first part of J.R.R. Tolkien''s epic fantasy trilogy.', 22.00, 'Fantasy', 'fellowship_of_the_ring.jpg'),
    ('The Seven Husbands of Evelyn Hugo', 'A dramatic tale of love, ambition, and Hollywood glamour.', 16.75, 'Romance', 'seven_husbands_of_evelyn_hugo.jpg'),
    ('It Ends With Us', 'An emotionally charged story about love and difficult choices.', 14.99, 'Romance', 'it_ends_with_us.jpg'),
    ('The Maze Runner', 'A thrilling dystopian adventure of survival in a mysterious labyrinth.', 15.00, 'Young Adult', 'maze_runner.jpg'),
    ('Outliers', 'Malcolm Gladwell examines the hidden factors behind extraordinary success.', 17.99, 'Non-Fiction', 'outliers.jpg'),
    ('Crying in H Mart', 'A memoir exploring food, identity, and familial relationships.', 19.95, 'Memoir', 'crying_in_h_mart.jpg'),
    ('The 5 AM Club', 'A guide to mastering your mornings and elevating your life.', 20.50, 'Self-help', '5_am_club.jpg'),
    ('Percy Jackson & The Olympians: The Lightning Thief', 'A modern twist on Greek mythology featuring a teenage hero.', 12.99, 'Fantasy', 'lightning_thief.jpg'),
    ('Brave New World', 'A dystopian classic about a futuristic world driven by technology and control.', 15.75, 'Science Fiction', 'brave_new_world.jpg'),
    ('The Sun and Her Flowers', 'A collection of poetry exploring growth, healing, and ancestry.', 13.99, 'Poetry', 'the_sun_and_her_flowers.jpg'),
    ('The Giver', 'A dystopian tale about a boy chosen to inherit the memories of a utopian society.', 10.75, 'Young Adult', 'the_giver.jpg'),
    ('The Shadow of the Wind', 'A mystery about a forgotten book and the secrets it unravels.', 14.95, 'Historical Fiction', 'shadow_of_the_wind.jpg'),
    ('The Four Agreements', 'A practical guide to personal freedom based on ancient Toltec wisdom.', 12.50, 'Self-help', 'four_agreements.jpg'),
    ('The Name of the Wind', 'An epic fantasy about a gifted young musician and magician.', 17.25, 'Fantasy', 'name_of_the_wind.jpg'),
    ('The House in the Cerulean Sea', 'A heartwarming story about discovering family in unexpected places.', 16.00, 'Fantasy', 'cerulean_sea.jpg'),
    ('Dark Matter', 'A gripping science fiction thriller about alternate realities.', 15.50, 'Science Fiction', 'dark_matter.jpg'),
    ('Norwegian Wood', 'A nostalgic and melancholic tale of love and loss.', 14.75, 'Fiction', 'norwegian_wood.jpg'),
    ('Big Magic', 'Elizabeth Gilbert''s insights on creativity and inspiration.', 18.99, 'Non-Fiction', 'big_magic.jpg'),
    ('Life of Pi', 'A survival story about a boy stranded on a lifeboat with a tiger.', 13.50, 'Adventure', 'life_of_pi.jpg'),
    ('The Handmaid''s Tale', 'A dystopian novel about a theocratic society and the oppression of women.', 14.50, 'Dystopian', 'handmaids_tale.jpg'),
    ('Inferno', 'A thrilling mystery inspired by Dante''s Divine Comedy.', 15.75, 'Thriller', 'inferno.jpg'),
    ('The Night Circus', 'A magical tale of a circus that opens only at night.', 18.99, 'Fantasy', 'night_circus.jpg'),
    ('The Goldfinch', 'A Pulitzer Prize-winning story of loss, survival, and art.', 19.95, 'Fiction', 'goldfinch.jpg'),
    ('The Martian', 'A gripping tale of survival about an astronaut stranded on Mars.', 14.99, 'Science Fiction', 'the_martian.jpg'),
    ('Me Before You', 'A touching love story with a focus on tough life choices.', 13.75, 'Romance', 'me_before_you.jpg'),
    ('The Silent Patient', 'A psychological thriller about a woman who stops speaking after a shocking act.', 17.00, 'Thriller', 'silent_patient.jpg'),
    ('How to Win Friends and Influence People', 'A classic self-help guide on improving communication and relationships.', 11.99, 'Self-help', 'win_friends_influence_people.jpg'),
    ('Milk and Honey', 'A collection of poetry and prose about love, loss, and healing.', 12.50, 'Poetry', 'milk_and_honey.jpg'),
    ('The Water Dancer', 'A powerful story of resistance and liberation set during slavery in America.', 16.99, 'Historical Fiction', 'water_dancer.jpg'),
    ('Shantaram', 'An epic tale of love, forgiveness, and adventure set in India.', 18.99, 'Fiction', 'shantaram.jpg'),
    ('The Celestine Prophecy', 'A spiritual journey exploring the mysteries of human energy and purpose.', 13.50, 'Spirituality', 'celestine_prophecy.jpg'),
    ('The Art of Happiness', 'The Dalai Lama''s insights on achieving enduring happiness.', 15.75, 'Philosophy', 'art_of_happiness.jpg'),
    ('The Outsiders', 'A story of friendship and class struggle among teens in the 1960s.', 10.99, 'Young Adult', 'the_outsiders.jpg'),
    ('The Midnight Bargain', 'A fantasy novel about magic, romance, and defying societal norms.', 16.25, 'Fantasy', 'midnight_bargain.jpg'),
    ('Before We Were Strangers', 'A heartwarming second-chance romance story.', 14.50, 'Romance', 'before_we_were_strangers.jpg'),
    ('The Science of Interstellar', 'A guide to the science behind the movie Interstellar.', 18.25, 'Science', 'science_of_interstellar.jpg'),
    ('The Queen''s Gambit', 'The story of a chess prodigy navigating life and the competitive world of chess.', 14.75, 'Fiction', 'queens_gambit.jpg'),
    ('Project Hail Mary', 'An astronaut''s thrilling mission to save humanity from extinction.', 19.50, 'Science Fiction', 'project_hail_mary.jpg'),
    ('Wild', 'A memoir of solo hiking and self-discovery on the Pacific Crest Trail.', 15.99, 'Memoir', 'wild.jpg'),
    ('The Paris Library', 'A heartfelt story of friendship and courage during World War II.', 16.75, 'Historical Fiction', 'paris_library.jpg'),
    ('The Overstory', 'An intricate tale of the connection between people and trees.', 19.50, 'Fiction', 'the_overstory.jpg'),
    ('Grit', 'A study on perseverance and passion for long-term goals.', 14.99, 'Self-help', 'grit.jpg'),
    ('Circe', 'A retelling of the mythological witch Circe from her perspective.', 18.99, 'Fantasy', 'circe.jpg'),
    ('The Midnight Children', 'A magical realist story about India''s transition to independence.', 15.25, 'Magical Realism', 'midnight_children.jpg'),
    ('The Vanishing Half', 'A story of twin sisters who choose radically different lives.', 17.99, 'Fiction', 'vanishing_half.jpg'),
    ('The Light We Carry', 'Michelle Obama''s reflections on resilience and hope.', 20.25, 'Memoir', 'light_we_carry.jpg'),
    ('Kafka on the Shore', 'A surreal journey blending dreams and reality.', 16.00, 'Fiction', 'kafka_on_the_shore.jpg'),
    ('The Comfort Book', 'A collection of consolations and reflections on hope.', 12.50, 'Non-Fiction', 'comfort_book.jpg'),
    ('Lessons in Chemistry', 'A witty tale about a scientist turned television cooking show star.', 19.25, 'Humor', 'lessons_in_chemistry.jpg'),
    ('The Mountain Is You', 'A self-help book about turning self-sabotage into self-mastery.', 14.99, 'Self-help', 'mountain_is_you.jpg'),
    ('Verity', 'A gripping and dark romantic thriller full of shocking twists.', 18.50, 'Thriller', 'verity.jpg'),
    ('Daisy Jones & The Six', 'A fictional story of a rock band navigating fame and heartbreak.', 17.99, 'Fiction', 'daisy_jones_six.jpg'),
    ('The Paper Palace', 'A compelling tale of love, secrets, and family legacy.', 16.75, 'Drama', 'paper_palace.jpg'),
    ('Think Like a Monk', 'A guide to finding purpose and peace inspired by monastic principles.', 15.50, 'Spirituality', 'think_like_a_monk.jpg'),
    ('The Lost Apothecary', 'A mystery set in both modern-day London and 18th-century apothecaries.', 19.25, 'Historical Fiction', 'lost_apothecary.jpg'),
    ('The Atlas Six', 'A dark academia fantasy about a secret society of magical elites.', 20.00, 'Fantasy', 'atlas_six.jpg'),
    ('Before the Coffee Gets Cold', 'A moving story about time travel and unfinished business.', 13.50, 'Fiction', 'before_coffee_gets_cold.jpg'),
    ('The Broken Earth Trilogy', 'A powerful science fiction series exploring societal collapse and survival.', 25.99, 'Science Fiction', 'broken_earth.jpg'),
    ('The Stranger', 'A philosophical exploration of existentialism and alienation.', 10.99, 'Philosophy', 'the_stranger.jpg'),
    ('The Paris Library', 'A heartfelt tale of resistance, love, and books during World War II.', 16.50, 'Historical Fiction', 'paris_library.jpg'),
    ('The Song of Achilles', 'A retelling of the Iliad through the lens of love and destiny.', 15.99, 'Fantasy', 'song_of_achilles.jpg'),
    ('Beach Read', 'A witty romance about two authors swapping genres for a summer.', 14.75, 'Romance', 'beach_read.jpg'),
    ('The Henna Artist', 'A vivid story of a woman building her life in post-independence Jaipur.', 13.99, 'Historical Fiction', 'henna_artist.jpg'),
    ('The Psychology of Money', 'Timeless lessons on wealth, greed, and happiness.', 18.25, 'Finance', 'psychology_of_money.jpg'),
    ('Breath: The New Science of a Lost Art', 'A fascinating exploration of the science behind proper breathing.', 16.00, 'Health', 'breath.jpg'),
    ('The 48 Laws of Power', 'A guide to achieving and maintaining power through strategic thinking.', 20.50, 'Self-help', '48_laws_of_power.jpg'),
    ('The Last House on Needless Street', 'A dark, twisty thriller about secrets and survival.', 17.99, 'Thriller', 'last_house_on_needless_street.jpg'),
    ('The Priory of the Orange Tree', 'An epic feminist fantasy full of dragons and intrigue.', 21.25, 'Fantasy', 'priory_orange_tree.jpg'),
    ('Man''s Search for Meaning', 'Viktor Frankl''s memoir and lessons from surviving the Holocaust.', 12.99, 'Philosophy', 'mans_search_for_meaning.jpg'),
    ('Anxious People', 'A quirky and heartfelt story about a failed bank robbery and its aftermath.', 14.50, 'Fiction', 'anxious_people.jpg'),
    ('The Night Watchman', 'A novel inspired by the life of the author''s grandfather, a Native American leader.', 16.75, 'Historical Fiction', 'night_watchman.jpg'),
    ('The Chain', 'A chilling thriller about the lengths parents will go to save their children.', 15.99, 'Thriller', 'the_chain.jpg'),
    ('Untamed', 'Glennon Doyle''s inspiring memoir about living authentically.', 18.25, 'Memoir', 'untamed.jpg'),
    ('Eleanor Oliphant Is Completely Fine', 'A quirky and heartwarming novel about loneliness and friendship.', 13.75, 'Fiction', 'eleanor_oliphant.jpg'),
    ('The Book of Joy', 'A dialogue between the Dalai Lama and Desmond Tutu on finding happiness.', 16.99, 'Spirituality', 'book_of_joy.jpg'),
    ('The House of the Spirits', 'A multi-generational tale of love, politics, and magic.', 14.50, 'Magical Realism', 'house_of_spirits.jpg'),
    ('Red Queen', 'A thrilling fantasy about power, rebellion, and betrayal.', 15.75, 'Young Adult', 'red_queen.jpg'),
    ('The Power', 'A speculative novel imagining a world where women develop a deadly new power.', 17.25, 'Science Fiction', 'the_power.jpg'),
    ('Maybe You Should Talk to Someone', 'A therapist''s reflections on her own life and her patients'' journeys.', 18.50, 'Memoir', 'talk_to_someone.jpg'),
    ('The Ocean at the End of the Lane', 'A haunting tale of memory and childhood by Neil Gaiman.', 14.25, 'Fantasy', 'ocean_at_end_of_lane.jpg'),
    ('Atomic Women', 'The untold stories of women in the atomic age.', 19.00, 'History', 'atomic_women.jpg'),
    ('The Couple Next Door', 'A suspenseful thriller about a crime that shocks a neighborhood.', 16.75, 'Thriller', 'couple_next_door.jpg'),
    ('Ikigai', 'A guide to finding purpose and joy in everyday life.', 13.50, 'Self-help', 'ikigai.jpg'),
    ('No Longer Human', 'An introspective and haunting novel about alienation and despair.', 11.99, 'Classics', 'no_longer_human.jpg'),
    ('A Court of Thorns and Roses', 'A captivating fantasy romance inspired by Beauty and the Beast.', 18.25, 'Fantasy', 'court_of_thorns_and_roses.jpg'),
    ('When Breath Becomes Air', 'A moving memoir by a neurosurgeon facing his own mortality.', 15.50, 'Memoir', 'when_breath_becomes_air.jpg'),
    ('The Wind-Up Bird Chronicle', 'A surreal and intricate novel about a man searching for his wife.', 16.99, 'Fiction', 'wind_up_bird.jpg'),
    ('The Rosie Project', 'A quirky romantic comedy about a genetics professor searching for love.', 14.50, 'Romance', 'rosie_project.jpg'),
    ('We Were Liars', 'A suspenseful and twisty tale about a wealthy family''s secrets.', 12.99, 'Young Adult', 'we_were_liars.jpg'),
    ('The Happiness Hypothesis', 'A psychological exploration of ancient wisdom and happiness.', 17.75, 'Psychology', 'happiness_hypothesis.jpg'),
    ('The Immortal Life of Henrietta Lacks', 'The story of a woman whose cells changed science forever.', 13.25, 'Biography', 'henrietta_lacks.jpg'),
    ('Girl, Wash Your Face', 'An empowering self-help book about overcoming challenges.', 14.75, 'Self-help', 'girl_wash_your_face.jpg'),
    ('The Secret Keeper', 'A compelling family mystery spanning decades.', 16.25, 'Historical Fiction', 'secret_keeper.jpg'),
    ('All the Light We Cannot See', 'A beautiful and heartbreaking story set during World War II.', 18.75, 'Historical Fiction', 'all_the_light.jpg'),
    ('Cloud Atlas', 'A complex tale weaving together six interconnected narratives.', 18.50, 'Fiction', 'cloud_atlas.jpg'),
    ('Pachinko', 'An epic historical novel following four generations of a Korean family.', 17.25, 'Historical Fiction', 'pachinko.jpg'),
    ('The Harbinger', 'A fascinating tale blending mystery, prophecy, and spirituality.', 14.99, 'Spirituality', 'the_harbinger.jpg'),
    ('Animal Farm', 'A political allegory about power and corruption.', 10.50, 'Classics', 'animal_farm.jpg'),
    ('Aristotle and Dante Discover the Secrets of the Universe', 'A heartfelt story of friendship and self-discovery.', 15.75, 'Young Adult', 'aristotle_and_dante.jpg'),
    ('The Testaments', 'A thrilling sequel to Margaret Atwood''s The Handmaid''s Tale.', 16.99, 'Dystopian', 'the_testaments.jpg'),
    ('The Alchemy of Air', 'The story of a scientific breakthrough that changed the world.', 12.99, 'History', 'alchemy_of_air.jpg'),
    ('Before I Go to Sleep', 'A gripping psychological thriller about memory and identity.', 14.25, 'Thriller', 'before_i_go_to_sleep.jpg'),
    ('The Pillars of the Earth', 'An epic tale of ambition and construction in medieval England.', 19.75, 'Historical Fiction', 'pillars_of_the_earth.jpg'),
    ('Never Let Me Go', 'A haunting story of love and ethics in a dystopian society.', 13.50, 'Science Fiction', 'never_let_me_go.jpg'),
    ('To Sleep in a Sea of Stars', 'A space epic full of discovery, conflict, and alien worlds.', 20.50, 'Science Fiction', 'sea_of_stars.jpg'),
    ('Little Fires Everywhere', 'A complex story of family, race, and privilege in suburban America.', 16.75, 'Fiction', 'little_fires_everywhere.jpg'),
    ('11/22/63', 'A thrilling time travel novel about preventing JFK''s assassination.', 18.25, 'Historical Fiction', '11_22_63.jpg'),
    ('The Midnight Watch', 'A captivating story surrounding the Titanic disaster.', 13.75, 'Historical Fiction', 'midnight_watch.jpg'),
    ('The Forest of Enchantments', 'A retelling of the Ramayana from Sita''s perspective.', 15.50, 'Fantasy', 'forest_of_enchantments.jpg'),
    ('The Paris Hours', 'A novel of intersecting lives in post-World War I Paris.', 14.50, 'Historical Fiction', 'paris_hours.jpg'),
    ('The Age of Surveillance Capitalism', 'An analysis of how big tech companies monetize personal data.', 21.00, 'Non-Fiction', 'surveillance_capitalism.jpg'),
    ('Homegoing', 'A sweeping tale of the descendants of two Ghanaian half-sisters.', 16.50, 'Historical Fiction', 'homegoing.jpg'),
    ('The Tattooist of Auschwitz', 'A love story set in one of the darkest periods of history.', 14.99, 'Historical Fiction', 'tattooist_of_auschwitz.jpg'),
    ('Legends & Lattes', 'A cozy fantasy about an orc retiring to open a coffee shop.', 13.25, 'Fantasy', 'legends_and_lattes.jpg'),
    ('The Invention of Wings', 'An inspiring tale of friendship and the fight for freedom.', 16.99, 'Historical Fiction', 'invention_of_wings.jpg'),
    ('The Glass Castle', 'A powerful memoir of resilience and unconventional upbringing.', 14.99, 'Memoir', 'glass_castle.jpg'),
    ('Evil Under the Sun', 'A classic Hercule Poirot mystery set on a sunny island.', 12.75, 'Mystery', 'evil_under_the_sun.jpg'),
    ('The Graveyard Book', 'A magical and heartwarming story of a boy raised in a graveyard.', 13.99, 'Fantasy', 'graveyard_book.jpg'),
    ('The 5 Love Languages', 'A guide to building stronger relationships through understanding love languages.', 11.50, 'Self-help', 'five_love_languages.jpg'),
    ('The Lighthouse Keeper''s Daughter', 'A historical tale of love, duty, and courage.', 15.75, 'Historical Fiction', 'lighthouse_keeper.jpg'),
    ('The Family Upstairs', 'A chilling and twisty thriller about family secrets.', 16.50, 'Thriller', 'family_upstairs.jpg'),
    ('The City We Became', 'A thrilling urban fantasy where cities come alive.', 18.25, 'Fantasy', 'city_we_became.jpg'),
    ('Howl''s Moving Castle', 'A whimsical fantasy adventure full of magic and heart.', 14.50, 'Fantasy', 'howls_moving_castle.jpg'),
    ('Quiet', 'An exploration of the power of introverts in a world that values extroversion.', 17.00, 'Psychology', 'quiet.jpg'),
    ('The House of Gucci', 'A captivating story of fashion, murder, and family legacy.', 19.99, 'Biography', 'house_of_gucci.jpg'),
    ('The Last Wish', 'A collection of thrilling adventures featuring Geralt of Rivia.', 16.25, 'Fantasy', 'last_wish.jpg'),
    ('The Devil in the White City', 'A gripping historical tale of a serial killer at the 1893 Chicago World''s Fair.', 14.99, 'History', 'devil_in_white_city.jpg'),
    ('The Magic of Thinking Big', 'A motivational book about setting and achieving big goals.', 13.75, 'Self-help', 'magic_of_thinking_big.jpg'),
    ('The Midnight Library', 'A novel exploring the infinite possibilities of life choices.', 15.00, 'Fiction', 'midnight_library.jpg'),
    ('The Nightingale', 'A story of two sisters navigating life during World War II.', 18.50, 'Historical Fiction', 'nightingale.jpg'),
    ('Beneath a Scarlet Sky', 'An incredible tale of courage during the Italian resistance in World War II.', 16.75, 'Historical Fiction', 'beneath_scarlet_sky.jpg'),
    ('Hyperion', 'A science fiction masterpiece blending mystery and mythology.', 18.99, 'Science Fiction', 'hyperion.jpg'),
    ('The Road to Unfreedom', 'A compelling analysis of the rise of authoritarianism.', 15.50, 'Politics', 'road_to_unfreedom.jpg'),
    ('Mexican Gothic', 'A chilling gothic horror set in 1950s Mexico.', 14.25, 'Horror', 'mexican_gothic.jpg'),
    ('The Four Winds', 'A gripping tale of hardship and resilience during the Dust Bowl era.', 15.99, 'Historical Fiction', 'the_four_winds.jpg'),
    ('Song of Solomon', 'A powerful exploration of African American identity and family heritage.', 14.75, 'Fiction', 'song_of_solomon.jpg'),
    ('The Wright Brothers', 'An inspiring biography of the pioneers of flight.', 18.50, 'Biography', 'wright_brothers.jpg'),
    ('The Light Between Oceans', 'A haunting story of love, sacrifice, and moral dilemmas.', 16.25, 'Drama', 'light_between_oceans.jpg'),
    ('The Song of the Jade Lily', 'A moving dual-timeline novel set in wartime Shanghai.', 15.50, 'Historical Fiction', 'song_of_the_jade_lily.jpg'),
    ('All the Ugly and Wonderful Things', 'A controversial and heart-wrenching story of love and survival.', 17.99, 'Fiction', 'ugly_and_wonderful_things.jpg'),
    ('The Art of Thinking Clearly', 'A practical guide to avoiding common cognitive biases.', 12.75, 'Self-help', 'art_of_thinking_clearly.jpg'),
    ('The Secret Life of Bees', 'A beautiful story about sisterhood and the search for belonging.', 14.50, 'Fiction', 'secret_life_of_bees.jpg'),
    ('The Shadow King', 'A powerful tale of female fighters during Ethiopia''s resistance to Italian invasion.', 18.00, 'Historical Fiction', 'shadow_king.jpg'),
    ('A Discovery of Witches', 'An enchanting tale of history, science, and forbidden love.', 16.75, 'Fantasy', 'discovery_of_witches.jpg'),
    ('Before We Were Strangers', 'A heartfelt story of a second chance at love.', 14.99, 'Romance', 'before_we_were_strangers.jpg'),
    ('Can''t Hurt Me', 'A motivational memoir by David Goggins about overcoming challenges.', 19.25, 'Memoir', 'cant_hurt_me.jpg'),
    ('Everything I Never Told You', 'A poignant story of family, secrets, and loss.', 13.99, 'Fiction', 'everything_i_never_told_you.jpg'),
    ('Stamped from the Beginning', 'A comprehensive history of racist ideas in America.', 22.50, 'History', 'stamped_from_the_beginning.jpg'),
    ('The Chain of Gold', 'A spellbinding fantasy set in a world of shadowhunters.', 17.25, 'Fantasy', 'chain_of_gold.jpg'),
    ('The Woman in the Window', 'A psychological thriller about secrets and deception.', 15.99, 'Thriller', 'woman_in_the_window.jpg'),
    ('The Seven Deaths of Evelyn Hardcastle', 'A mind-bending murder mystery with a time twist.', 14.75, 'Mystery', 'seven_deaths_evelyn_hardcastle.jpg'),
    ('Open Book', 'A raw and inspiring memoir by Jessica Simpson.', 18.50, 'Memoir', 'open_book.jpg'),
    ('Caste', 'An insightful examination of the unspoken caste system in America.', 20.00, 'Non-Fiction', 'caste.jpg'),
    ('Beach Read', 'A witty romance between two authors trying to write in opposite genres.', 13.99, 'Romance', 'beach_read.jpg'),
    ('The Hundred-Year-Old Man Who Climbed Out the Window and Disappeared', 'A hilarious and quirky adventure of a centenarian on the run.', 14.99, 'Fiction', 'hundred_year_old_man.jpg'),
    ('The Light of Days', 'An inspiring account of female resistance fighters in World War II.', 17.50, 'History', 'light_of_days.jpg'),
    ('The Paper Palace', 'A tale of family secrets and a summer that changes everything.', 15.75, 'Drama', 'paper_palace.jpg'),
    ('Heartstopper', 'A heartwarming graphic novel about friendship and love.', 13.99, 'Young Adult', 'heartstopper.jpg'),
    ('Shatter Me', 'A dystopian romance about a girl whose touch is lethal.', 16.00, 'Science Fiction', 'shatter_me.jpg'),
    ('The Paris Secret', 'A gripping dual-timeline story of hidden wartime secrets.', 15.25, 'Historical Fiction', 'paris_secret.jpg'),
    ('The Man Who Mistook His Wife for a Hat', 'A fascinating collection of case studies in neurology.', 14.50, 'Science', 'man_mistook_hat.jpg'),
    ('Clockwork Angel', 'A captivating fantasy set in Victorian London.', 17.25, 'Fantasy', 'clockwork_angel.jpg'),
    ('The Alice Network', 'A thrilling story of female spies during the World Wars.', 16.50, 'Historical Fiction', 'alice_network.jpg'),
    ('We Begin at the End', 'A deeply moving tale of love, loss, and redemption.', 18.75, 'Fiction', 'we_begin_at_the_end.jpg');